

global:
  smtp_smarthost: 
  smtp_from: 
  smtp_require_tls: true
  smtp_hello: 
  smtp_auth_username: 
  smtp_auth_password: 

route:
  group_by: ['instance', 'alert']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 

receivers:
- name: 
  email_configs:
  - to: 
    from: 
    smarthost: 
    auth_username: 
    auth_identity: 
    auth_password: 
